name: Daily Quote for discord bot


on:
    schedule:
        - cron: '0 12 * * *'  # Runs every day at 12:00 UTC (9:00 brasilia time)
    workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
    send-quote:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install requests

            - name: Send daily quote
              env: 
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              run: python quote_of_the_day.py
